// Generated by CoffeeScript 1.6.3
var Client, DbManager, helpers, _ref, _ref1, _ref2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Client = require('request-json').JsonClient;

helpers = require('./helpers');

DbManager = (function() {
  function DbManager() {
    this.dbClient = new Client("http://localhost:9101/");
    this.name = process.env.NAME;
    this.token = process.env.TOKEN;
    if (process.env.NODE_ENV === "production" || process.env.NODE_ENV === "test") {
      this.dbClient.setBasicAuth(this.name, this.token);
    }
  }

  DbManager.prototype.all = function(callback) {
    var path,
      _this = this;
    path = "request/" + (this.type.toLowerCase()) + "/all/";
    return this.dbClient.post(path, {}, function(err, response, models) {
      if (err) {
        return callback(err);
      } else if (response.statusCode !== 200) {
        return callback(new Error(models));
      } else {
        return callback(null, models);
      }
    });
  };

  DbManager.prototype.create = function(model, callback) {
    var _this = this;
    model.docType = this.type;
    return this.dbClient.post("data/", model, function(err, response, model) {
      if (err) {
        return callback(err, 500);
      } else if (response.statusCode !== 201) {
        return callback(new Error("Error occured"), response.statusCode);
      } else {
        return callback(null, 201, model);
      }
    });
  };

  DbManager.prototype.merge = function(model, data, callback) {
    var _this = this;
    return this.dbClient.put("data/merge/" + model._id + "/", data, function(err, res, body) {
      if (err) {
        return callback(err);
      } else if (res.statusCode === 404) {
        return callback(new Error("Model does not exist"));
      } else if (res.statusCode !== 200) {
        return callback(new Error(body));
      } else {
        return callback(null);
      }
    });
  };

  DbManager.prototype.deleteAll = function(callback) {
    var path;
    path = "request/" + (this.type.toLowerCase()) + "/all/destroy/";
    return this.dbClient.put(path, {}, function(err, response) {
      if (err) {
        return callback(err);
      } else if (response.statusCode !== 204) {
        return callback(new Error("Server error"));
      } else {
        return callback(null);
      }
    });
  };

  return DbManager;

})();

exports.UserManager = (function(_super) {
  __extends(UserManager, _super);

  function UserManager() {
    _ref = UserManager.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  UserManager.prototype.type = 'User';

  UserManager.prototype.isValid = function(user) {
    if ((user.password != null) && user.password.length > 4) {
      if (helpers.checkMail(user.email)) {
        this.error = null;
        return true;
      } else {
        this.error = 'Wrong email format';
        return false;
      }
    } else {
      this.error = 'Password is too short';
      return false;
    }
  };

  UserManager.prototype.createUser = function(model, callback) {
    var _this = this;
    model.docType = this.type;
    return this.dbClient.post("user/", model, function(err, response, model) {
      console.log(err);
      if (err) {
        return callback(err, 500);
      } else if (response.statusCode !== 201) {
        return callback(new Error("Error occured"), response.statusCode);
      } else {
        return callback(null, 201, model);
      }
    });
  };

  UserManager.prototype.mergeUser = function(model, data, callback) {
    var _this = this;
    return this.dbClient.put("user/merge/" + model._id + "/", data, function(err, res, body) {
      if (err) {
        return callback(err);
      } else if (res.statusCode === 404) {
        return callback(new Error("Model does not exist"));
      } else if (res.statusCode !== 200) {
        return callback(new Error(body));
      } else {
        return callback(null);
      }
    });
  };

  UserManager.prototype.getUser = function(callback) {
    return this.all(function(err, users) {
      if (err) {
        return callback(err);
      } else if (users.length === 0) {
        return callback(null, null);
      } else {
        return callback(null, users[0]);
      }
    });
  };

  return UserManager;

})(DbManager);

exports.DeviceManager = (function(_super) {
  __extends(DeviceManager, _super);

  function DeviceManager() {
    _ref1 = DeviceManager.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  DeviceManager.prototype.type = 'Device';

  DeviceManager.prototype.allDevice = [];

  DeviceManager.prototype.update = function() {
    var _this = this;
    this.allDevice = [];
    return this.all(function(err, devices) {
      var device, _i, _len, _results;
      if (err) {
        console.log(err);
      }
      if (devices) {
        _results = [];
        for (_i = 0, _len = devices.length; _i < _len; _i++) {
          device = devices[_i];
          device = device.value;
          _results.push(_this.allDevice[device.login] = device.password);
        }
        return _results;
      }
    });
  };

  DeviceManager.prototype.isAuthenticated = function(username, password, callback) {
    return callback((this.allDevice[username] != null) && (this.allDevice[username] === password));
  };

  return DeviceManager;

})(DbManager);

exports.InstanceManager = (function(_super) {
  __extends(InstanceManager, _super);

  function InstanceManager() {
    _ref2 = InstanceManager.__super__.constructor.apply(this, arguments);
    return _ref2;
  }

  InstanceManager.prototype.type = 'CozyInstance';

  return InstanceManager;

})(DbManager);
