// Generated by CoffeeScript 1.6.2
var Client, PasswordKeys;

Client = require("request-json").JsonClient;

module.exports = PasswordKeys = (function() {
  function PasswordKeys() {
    this.client = new Client("http://localhost:9101/");
    this.name = process.env.NAME;
    this.token = process.env.TOKEN;
    if (process.env.NODE_ENV === "production" || process.env.NODE_ENV === "test") {
      this.client.setBasicAuth(this.name, this.token);
    }
  }

  PasswordKeys.prototype.initializeKeys = function(pwd, callback) {
    var _this = this;

    return this.client.post("accounts/password/", {
      password: pwd
    }, function(err, res, body) {
      if (err) {
        return callback(err);
      } else {
        return callback();
      }
    });
  };

  PasswordKeys.prototype.updateKeys = function(pwd, callback) {
    var _this = this;

    return this.client.put("accounts/password/", {
      password: pwd
    }, function(err, res, body) {
      if (err) {
        return callback(err);
      } else {
        return callback();
      }
    });
  };

  PasswordKeys.prototype.deleteKeys = function(callback) {
    var _this = this;

    return this.client.del("accounts/", function(err, res, body) {
      if (err) {
        return callback(err);
      } else {
        return callback();
      }
    });
  };

  PasswordKeys.prototype.resetKeys = function(callback) {
    var _this = this;

    return this.client.del("accounts/reset/", function(err, res, body) {
      if (err) {
        return callback(err);
      } else {
        return callback();
      }
    });
  };

  return PasswordKeys;

})();
